<?php

namespace Database\Seeders;

use App\Models\Species;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class SpeciesSeeder extends Seeder
{
    /**
     * Seed the species reference catalog with real, named species — no
     * generated/fake data. Sunlight, watering cadence, native region, and
     * care difficulty reflect widely-documented horticultural facts.
     *
     * `co2_offset_kg_per_year` figures are approximate, illustrative
     * estimates for a young-to-medium specimen (commonly-cited ranges vary
     * by source, climate, and plant age/size) — trees offset meaningfully
     * more than shrubs, which offset more than small houseplants; treat
     * these as directional, not lab-measured figures.
     */
    public function run(): void
    {
        $species = [
            // Trees
            [
                'name' => 'Neem',
                'scientific_name' => 'Azadirachta indica',
                'category' => 'tree',
                'description' => 'A fast-growing, drought-tolerant tree valued for its air-purifying and pest-repelling properties.',
                'sunlight' => 'full_sun',
                'water_frequency_days' => 5,
                'native_region' => 'South Asia',
                'co2_offset_kg_per_year' => 21.77,
                'care_difficulty' => 'easy',
            ],
            [
                'name' => 'Gulmohar',
                'scientific_name' => 'Delonix regia',
                'category' => 'tree',
                'description' => 'A striking flowering tree with a broad canopy, known for vivid red-orange blooms.',
                'sunlight' => 'full_sun',
                'water_frequency_days' => 4,
                'native_region' => 'Madagascar (naturalized in South Asia)',
                'co2_offset_kg_per_year' => 18.50,
                'care_difficulty' => 'moderate',
            ],
            [
                'name' => 'Peepal',
                'scientific_name' => 'Ficus religiosa',
                'category' => 'tree',
                'description' => 'A large, long-lived sacred fig with a broad canopy; fast-growing once established.',
                'sunlight' => 'full_sun',
                'water_frequency_days' => 5,
                'native_region' => 'Indian subcontinent',
                'co2_offset_kg_per_year' => 20.00,
                'care_difficulty' => 'easy',
            ],
            [
                'name' => 'Banyan',
                'scientific_name' => 'Ficus benghalensis',
                'category' => 'tree',
                'description' => 'A massive, spreading shade tree with aerial prop roots; needs significant space to mature.',
                'sunlight' => 'full_sun',
                'water_frequency_days' => 6,
                'native_region' => 'Indian subcontinent',
                'co2_offset_kg_per_year' => 25.00,
                'care_difficulty' => 'moderate',
            ],
            [
                'name' => 'Mango',
                'scientific_name' => 'Mangifera indica',
                'category' => 'tree',
                'description' => 'A long-lived fruit tree with a dense canopy, widely grown for its edible fruit.',
                'sunlight' => 'full_sun',
                'water_frequency_days' => 4,
                'native_region' => 'South Asia',
                'co2_offset_kg_per_year' => 15.00,
                'care_difficulty' => 'moderate',
            ],
            [
                'name' => 'Jacaranda',
                'scientific_name' => 'Jacaranda mimosifolia',
                'category' => 'tree',
                'description' => 'An ornamental tree known for its vivid purple flower clusters in spring.',
                'sunlight' => 'full_sun',
                'water_frequency_days' => 5,
                'native_region' => 'South America (naturalized worldwide)',
                'co2_offset_kg_per_year' => 16.00,
                'care_difficulty' => 'moderate',
            ],
            [
                'name' => 'Amaltas',
                'scientific_name' => 'Cassia fistula',
                'category' => 'tree',
                'description' => 'The "golden shower tree" — known for cascading yellow flower clusters; tolerant of poor soil.',
                'sunlight' => 'full_sun',
                'water_frequency_days' => 5,
                'native_region' => 'South and Southeast Asia',
                'co2_offset_kg_per_year' => 14.00,
                'care_difficulty' => 'easy',
            ],
            [
                'name' => 'Eucalyptus',
                'scientific_name' => 'Eucalyptus globulus',
                'category' => 'tree',
                'description' => 'A very fast-growing evergreen tree with aromatic leaves; high water use once mature.',
                'sunlight' => 'full_sun',
                'water_frequency_days' => 6,
                'native_region' => 'Australia',
                'co2_offset_kg_per_year' => 22.00,
                'care_difficulty' => 'easy',
            ],
            [
                'name' => 'Ashoka Tree',
                'scientific_name' => 'Saraca asoca',
                'category' => 'tree',
                'description' => 'A slow-growing evergreen tree with fragrant orange-yellow flowers; culturally significant in South Asia.',
                'sunlight' => 'partial_shade',
                'water_frequency_days' => 4,
                'native_region' => 'Indian subcontinent',
                'co2_offset_kg_per_year' => 12.00,
                'care_difficulty' => 'moderate',
            ],
            [
                'name' => 'Sheesham',
                'scientific_name' => 'Dalbergia sissoo',
                'category' => 'tree',
                'description' => 'A fast-growing deciduous tree valued for timber and shade; tolerant of a wide range of soils.',
                'sunlight' => 'full_sun',
                'water_frequency_days' => 5,
                'native_region' => 'Indian subcontinent',
                'co2_offset_kg_per_year' => 19.00,
                'care_difficulty' => 'moderate',
            ],

            // Shrubs
            [
                'name' => 'Hibiscus',
                'scientific_name' => 'Hibiscus rosa-sinensis',
                'category' => 'shrub',
                'description' => 'A flowering shrub that attracts pollinators and blooms best with regular watering.',
                'sunlight' => 'partial_shade',
                'water_frequency_days' => 3,
                'native_region' => 'East Asia',
                'co2_offset_kg_per_year' => 5.40,
                'care_difficulty' => 'moderate',
            ],
            [
                'name' => 'Bougainvillea',
                'scientific_name' => 'Bougainvillea glabra',
                'category' => 'shrub',
                'description' => 'A vigorous, thorny climbing shrub with vivid papery bracts; thrives on neglect once established.',
                'sunlight' => 'full_sun',
                'water_frequency_days' => 5,
                'native_region' => 'South America',
                'co2_offset_kg_per_year' => 4.50,
                'care_difficulty' => 'easy',
            ],
            [
                'name' => 'Rose',
                'scientific_name' => 'Rosa × damascena',
                'category' => 'shrub',
                'description' => 'A fragrant flowering shrub that rewards regular feeding and pruning with prolific blooms.',
                'sunlight' => 'full_sun',
                'water_frequency_days' => 3,
                'native_region' => 'Middle East and Central Asia',
                'co2_offset_kg_per_year' => 3.20,
                'care_difficulty' => 'moderate',
            ],
            [
                'name' => 'Jasmine',
                'scientific_name' => 'Jasminum sambac',
                'category' => 'shrub',
                'description' => 'A fragrant flowering shrub/vine, popularly known as Chameli, that blooms through warm months.',
                'sunlight' => 'partial_shade',
                'water_frequency_days' => 3,
                'native_region' => 'South and Southeast Asia',
                'co2_offset_kg_per_year' => 3.00,
                'care_difficulty' => 'easy',
            ],
            [
                'name' => 'Oleander',
                'scientific_name' => 'Nerium oleander',
                'category' => 'shrub',
                'description' => 'A tough, drought-tolerant flowering shrub. Note: all parts are toxic if ingested — keep away from pets and children.',
                'sunlight' => 'full_sun',
                'water_frequency_days' => 5,
                'native_region' => 'Mediterranean region',
                'co2_offset_kg_per_year' => 4.00,
                'care_difficulty' => 'easy',
            ],
            [
                'name' => 'Curry Leaf Plant',
                'scientific_name' => 'Murraya koenigii',
                'category' => 'shrub',
                'description' => 'An aromatic culinary shrub whose leaves are a staple in South Asian cooking.',
                'sunlight' => 'partial_shade',
                'water_frequency_days' => 3,
                'native_region' => 'Indian subcontinent',
                'co2_offset_kg_per_year' => 2.50,
                'care_difficulty' => 'easy',
            ],

            // Houseplants
            [
                'name' => 'Money Plant',
                'scientific_name' => 'Epipremnum aureum',
                'category' => 'plant',
                'description' => 'A hardy trailing vine that tolerates low light and irregular watering.',
                'sunlight' => 'low_light',
                'water_frequency_days' => 7,
                'native_region' => 'Southeast Asia',
                'co2_offset_kg_per_year' => 2.10,
                'care_difficulty' => 'easy',
            ],
            [
                'name' => 'Snake Plant',
                'scientific_name' => 'Sansevieria trifasciata',
                'category' => 'plant',
                'description' => 'An extremely low-maintenance succulent that tolerates neglect and low light.',
                'sunlight' => 'low_light',
                'water_frequency_days' => 10,
                'native_region' => 'West Africa',
                'co2_offset_kg_per_year' => 1.20,
                'care_difficulty' => 'easy',
            ],
            [
                'name' => 'Peace Lily',
                'scientific_name' => 'Spathiphyllum wallisii',
                'category' => 'plant',
                'description' => 'A shade-loving houseplant with white blooms; droops visibly when it needs water.',
                'sunlight' => 'partial_shade',
                'water_frequency_days' => 5,
                'native_region' => 'Central and South America',
                'co2_offset_kg_per_year' => 1.50,
                'care_difficulty' => 'easy',
            ],
            [
                'name' => 'Aloe Vera',
                'scientific_name' => 'Aloe vera',
                'category' => 'plant',
                'description' => 'A succulent valued for its soothing gel; prefers to dry out fully between waterings.',
                'sunlight' => 'full_sun',
                'water_frequency_days' => 10,
                'native_region' => 'Arabian Peninsula',
                'co2_offset_kg_per_year' => 1.00,
                'care_difficulty' => 'easy',
            ],
            [
                'name' => 'Spider Plant',
                'scientific_name' => 'Chlorophytum comosum',
                'category' => 'plant',
                'description' => 'A fast-growing, pet-safe houseplant that readily produces small plantlets.',
                'sunlight' => 'partial_shade',
                'water_frequency_days' => 6,
                'native_region' => 'South Africa',
                'co2_offset_kg_per_year' => 1.30,
                'care_difficulty' => 'easy',
            ],
            [
                'name' => 'ZZ Plant',
                'scientific_name' => 'Zamioculcas zamiifolia',
                'category' => 'plant',
                'description' => 'A glossy-leaved houseplant built for neglect — stores water in its rhizomes.',
                'sunlight' => 'low_light',
                'water_frequency_days' => 14,
                'native_region' => 'East Africa',
                'co2_offset_kg_per_year' => 1.00,
                'care_difficulty' => 'easy',
            ],
            [
                'name' => 'Areca Palm',
                'scientific_name' => 'Dypsis lutescens',
                'category' => 'plant',
                'description' => 'A feathery, clumping palm that brings a tropical look indoors.',
                'sunlight' => 'partial_shade',
                'water_frequency_days' => 4,
                'native_region' => 'Madagascar',
                'co2_offset_kg_per_year' => 3.50,
                'care_difficulty' => 'moderate',
            ],
            [
                'name' => 'Rubber Plant',
                'scientific_name' => 'Ficus elastica',
                'category' => 'plant',
                'description' => 'A structural houseplant with broad, glossy leaves; grows into a small indoor tree over time.',
                'sunlight' => 'partial_shade',
                'water_frequency_days' => 5,
                'native_region' => 'South and Southeast Asia',
                'co2_offset_kg_per_year' => 4.00,
                'care_difficulty' => 'easy',
            ],
            [
                'name' => 'Philodendron',
                'scientific_name' => 'Philodendron hederaceum',
                'category' => 'plant',
                'description' => 'A trailing, heart-leafed houseplant that is forgiving of inconsistent care.',
                'sunlight' => 'low_light',
                'water_frequency_days' => 6,
                'native_region' => 'Central and South America',
                'co2_offset_kg_per_year' => 1.20,
                'care_difficulty' => 'easy',
            ],
            [
                'name' => 'Tulsi',
                'scientific_name' => 'Ocimum tenuiflorum',
                'category' => 'plant',
                'description' => 'Holy basil — a fast-growing aromatic herb, sacred in South Asian households and used in traditional remedies.',
                'sunlight' => 'full_sun',
                'water_frequency_days' => 2,
                'native_region' => 'Indian subcontinent',
                'co2_offset_kg_per_year' => 1.50,
                'care_difficulty' => 'easy',
            ],
        ];

        foreach ($species as $entry) {
            Species::query()->updateOrCreate(
                ['slug' => Str::slug($entry['name'])],
                [...$entry, 'slug' => Str::slug($entry['name'])]
            );
        }
    }
}
